# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YejcGQ0v55JxT9lZeZpNnU1TG2SZQEkq
"""

!pip -q install pulp qiskit qiskit-aer qiskit-ibm-runtime

import os
import re
import time
import math
import random
import warnings
from collections import defaultdict
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
import pulp
import matplotlib.pyplot as plt
from qiskit.circuit.library import efficient_su2
from qiskit.quantum_info import SparsePauliOp
from qiskit_aer.primitives import EstimatorV2 as AerEstimator

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
# os.environ["PYTHONHASHSEED"] = str(SEED)

# warnings.filterwarnings("ignore", category=UserWarning, module="pandas")
# pd.set_option("display.width", 180)
# pd.set_option("display.max_columns", 100)

# settings
PENALTY_RATE = 0.15
FILL_THRESHOLD = 0.95
NUMERICAL_TOLERANCE = 1e-6


BATCH_SIZE = 8
BATCH_MODE = "contested"

EXACT_ENUMERATION_LIMIT = 16

# PCE settings
PCE_DEGREE = 2
ANSATZ_REPS = 2
N_RESTARTS = 3
N_OUTER = 8
COBYLA_MAXITER = 300
COBYLA_TOL = 1e-4
PATIENCE = 3

ALPHA_C = 1.0
ALPHA_GROWTH = 1.30


AL_MU_DOCK = 10.0
AL_MU_CASE = 10.0
AL_MU_PALLET = 10.0

# Repeated noisy simulation settings
NOISE_TRIALS = 20
NOISE_SHOTS = 4096

# # Also write out anonymized copies suitable for slides / public write-ups.
# SAVE_PUBLIC_OUTPUTS = True

print("Seed:", SEED)
print("Requested batch size:", BATCH_SIZE)
print("Batch mode:", BATCH_MODE)



# Load the CSV files

SEARCH_ROOTS = [
    Path.cwd(),
    Path("/content"),
    Path("/content/drive/MyDrive"),
    Path("/mnt/data"),
]

def locate_csv(required_keywords, excluded_keywords=()):
    required_keywords = [k.lower() for k in required_keywords]
    excluded_keywords = [k.lower() for k in excluded_keywords]

    matches = []
    for root in SEARCH_ROOTS:
        if not root.exists():
            continue
        try:
            for path in root.rglob("*.csv"):
                name = path.name.lower()
                if (
                    all(k in name for k in required_keywords)
                    and not any(k in name for k in excluded_keywords)
                ):
                    matches.append(path)
        except PermissionError:
            continue

    # if not matches:
    #     raise FileNotFoundError(
    #         f"No CSV found with keywords {required_keywords}. "
    #         "Upload all five challenge CSV files and rerun this cell."
    #     )

    matches = sorted(matches, key=lambda p: (len(p.parts), len(p.name), str(p)))
    return matches[0]

file_paths = {
    "orders": locate_csv(["input", "order"], excluded_keywords=["output"]),
    "shipping": locate_csv(["shipping", "cost"]),
    "inventory": locate_csv(["capacity", "planning"]),
    "dock": locate_csv(["dock", "capacity"]),
    "throughput": locate_csv(["throughput", "capacity"]),
}

for label, path in file_paths.items():
    print(f"{label:12s}: {path}")

order_raw = pd.read_csv(file_paths["orders"])
ship_raw = pd.read_csv(file_paths["shipping"])
inv_raw = pd.read_csv(file_paths["inventory"])
dock_raw = pd.read_csv(file_paths["dock"])
throughput_raw = pd.read_csv(file_paths["throughput"])

print("\nRaw shapes")
print("orders     :", order_raw.shape)
print("shipping   :", ship_raw.shape)
print("inventory  :", inv_raw.shape)
print("dock       :", dock_raw.shape)
print("throughput :", throughput_raw.shape)


order = order_raw.copy()
ship = ship_raw.copy()
inv = inv_raw.copy()
dock = dock_raw.copy()
throughput = throughput_raw.copy()

for dataframe in [order, ship, inv, dock, throughput]:
    dataframe.columns = dataframe.columns.str.strip()

REQUIRED_COLUMNS = {
    "orders": [
        "Group_Flag", "Plant", "transportationplanningdate", "ZipCode",
        "OrderedQty_converted", "MaterialNumber", "Order_SKU_Revenue",
    ],
    "shipping": ["Plant", "TargetZip", "Shipping_Cost"],
    "inventory": ["LocationID", "MaterialID", "DATE", "Available_inventory"],
    "dock": ["Plant", "Date", "ActiveFlag", "Dock_Remaining"],
    "throughput": ["Plant", "util_case_picks", "util_pallets", "order_count"],
}

def check_columns(dataframe, label, required):
    missing = [column for column in required if column not in dataframe.columns]
    if missing:
        raise ValueError(
            f"{label} is missing columns {missing}. "
            f"Columns found: {list(dataframe.columns)}"
        )

for label, dataframe in [
    ("orders", order),
    ("shipping", ship),
    ("inventory", inv),
    ("dock", dock),
    ("throughput", throughput),
]:
    check_columns(dataframe, label, REQUIRED_COLUMNS[label])

def normalize_identifier(value):
    if pd.isna(value):
        return None
    text = str(value).strip()
    if re.fullmatch(r"-?\d+\.0+", text):
        text = text.split(".")[0]
    return text

def normalize_zip(value):
    if pd.isna(value):
        return None
    text = normalize_identifier(value)
    digits = re.sub(r"\D", "", text or "")
    return digits.zfill(5) if digits else None

def parse_date_column(dataframe, column, label):

    parsed = pd.to_datetime(
        dataframe[column],
        format="%Y-%m-%d",
        errors="coerce",
    )

    unresolved = parsed.isna() & dataframe[column].notna()
    if unresolved.any():
        try:
            fallback = pd.to_datetime(
                dataframe.loc[unresolved, column],
                format="mixed",
                errors="coerce",
            )
        except (TypeError, ValueError):
            fallback = pd.to_datetime(
                dataframe.loc[unresolved, column],
                errors="coerce",
            )
        parsed.loc[unresolved] = fallback

    parsed = parsed.dt.normalize()
    invalid = parsed.isna() & dataframe[column].notna()
    if invalid.any():
        print(f"Warning: dropping {int(invalid.sum())} invalid dates from {label}.")
    return parsed

order["Group_Flag"] = order["Group_Flag"].map(normalize_identifier)
order["Plant"] = order["Plant"].map(normalize_identifier)
order["MaterialNumber"] = order["MaterialNumber"].map(normalize_identifier)
order["ZipCode"] = order["ZipCode"].map(normalize_zip)

ship["Plant"] = ship["Plant"].map(normalize_identifier)
ship["TargetZip"] = ship["TargetZip"].map(normalize_zip)

inv["LocationID"] = inv["LocationID"].map(normalize_identifier)
inv["MaterialID"] = inv["MaterialID"].map(normalize_identifier)

dock["Plant"] = dock["Plant"].map(normalize_identifier)
throughput["Plant"] = throughput["Plant"].map(normalize_identifier)

order["transportationplanningdate"] = parse_date_column(
    order, "transportationplanningdate", "orders.transportationplanningdate"
)
inv["DATE"] = parse_date_column(inv, "DATE", "inventory.DATE")
dock["Date"] = parse_date_column(dock, "Date", "dock.Date")

throughput_date_col = next(
    (
        column
        for column in ["transportationplanningdate", "Date", "DATE", "date"]
        if column in throughput.columns
    ),
    None,
)
if throughput_date_col is None:
    raise ValueError(
        "The throughput file needs a date column named "
        "transportationplanningdate, Date, DATE, or date."
    )

throughput["Date"] = parse_date_column(
    throughput, throughput_date_col, f"throughput.{throughput_date_col}"
)

for column in ["OrderedQty_converted", "Order_SKU_Revenue"]:
    order[column] = pd.to_numeric(order[column], errors="coerce")

ship["Shipping_Cost"] = pd.to_numeric(ship["Shipping_Cost"], errors="coerce")
inv["Available_inventory"] = pd.to_numeric(
    inv["Available_inventory"], errors="coerce"
)
dock["Dock_Remaining"] = pd.to_numeric(dock["Dock_Remaining"], errors="coerce")

for column in ["util_case_picks", "util_pallets", "order_count"]:
    throughput[column] = pd.to_numeric(throughput[column], errors="coerce")

order = order.dropna(
    subset=[
        "Group_Flag", "Plant", "transportationplanningdate", "ZipCode",
        "MaterialNumber", "OrderedQty_converted", "Order_SKU_Revenue",
    ]
).copy()
order = order[order["OrderedQty_converted"] > 0].copy()

ship = ship.dropna(subset=["Plant", "TargetZip", "Shipping_Cost"]).copy()
inv = inv.dropna(
    subset=["LocationID", "MaterialID", "DATE", "Available_inventory"]
).copy()
dock = dock.dropna(subset=["Plant", "Date", "Dock_Remaining"]).copy()
throughput = throughput.dropna(
    subset=["Plant", "Date", "util_case_picks", "util_pallets", "order_count"]
).copy()

dock = dock[
    dock["ActiveFlag"].astype(str).str.strip().str.upper().eq("Y")
].copy()

inv["Available_inventory"] = inv["Available_inventory"].clip(lower=0)
dock["Dock_Remaining"] = dock["Dock_Remaining"].clip(lower=0)
for column in ["util_case_picks", "util_pallets", "order_count"]:
    throughput[column] = throughput[column].clip(lower=0)

shipping_cost = (
    ship.groupby(["Plant", "TargetZip"])["Shipping_Cost"].min().to_dict()
)
inventory = (
    inv.groupby(["LocationID", "MaterialID", "DATE"])["Available_inventory"]
    .sum()
    .to_dict()
)

dock_capacity = (
    dock.groupby(["Plant", "Date"])["Dock_Remaining"].sum().to_dict()
)

throughput_daily = throughput.groupby(["Plant", "Date"])[
    ["util_case_picks", "util_pallets", "order_count"]
].sum()

case_pick_capacity = throughput_daily["util_case_picks"].to_dict()
pallet_pick_capacity = throughput_daily["util_pallets"].to_dict()
order_count_capacity = throughput_daily["order_count"].to_dict()

all_dcs = sorted(set(order["Plant"].dropna()))


plants_with_dock_feed = set(dock["Plant"].unique())
plants_missing_dock_feed = set(all_dcs) - plants_with_dock_feed
# if plants_missing_dock_feed:
#     print(
#         "WARNING: no dock-capacity records exist for plant(s) "
#         f"{sorted(plants_missing_dock_feed)} on ANY date. Treating the dock "
#         "constraint as non-binding for these plants rather than silently using "
#         "order_count (a headcount, not a capacity figure) as a stand-in. "
#         "Get real dock-capacity data for these DCs before trusting diversion "
#         "recommendations that route into them."
#     )


UNCONSTRAINED_DOCK_CAPACITY = float(order["OrderedQty_converted"].sum())

def effective_order_capacity(dc, pgi_date):
    key = (dc, pgi_date)
    if key in dock_capacity:
        return float(dock_capacity[key])
    if dc in plants_missing_dock_feed:

        return UNCONSTRAINED_DOCK_CAPACITY

    return float(order_count_capacity.get(key, 0.0))

print("Cleaned order lines:", len(order))
print("Distinct orders:", order["Group_Flag"].nunique())
print("Distinct DCs:", len(all_dcs))

# %% Build option-level proxy metrics and divert candidates
def cases_per_pallet(line):
    for column in ["CasesPerPallet", "ProductCasesPerPallet", "cases_per_pallet"]:
        if column in line.index:
            value = pd.to_numeric(line[column], errors="coerce")
            if pd.notna(value) and float(value) > 0:
                return max(int(round(float(value))), 1)
    return 1

def get_unit_revenue(line):
    demand = float(line["OrderedQty_converted"])
    return float(line["Order_SKU_Revenue"]) / demand if demand > 0 else 0.0

def option_proxy_metrics(dc, pgi_date, zip_code, order_lines):
    line_rows = []
    total_demand = 0.0
    total_filled = 0.0
    fulfilled_revenue = 0.0
    case_picks = 0.0
    pallet_picks = 0.0

    for _, line in order_lines.iterrows():
        demand = max(float(line["OrderedQty_converted"]), 0.0)
        available = max(
            float(inventory.get((dc, line["MaterialNumber"], pgi_date), 0.0)),
            0.0,
        )
        filled = min(demand, available)
        cpp = cases_per_pallet(line)
        pallet_count = math.floor(filled / cpp)
        loose_count = filled - cpp * pallet_count
        unit_revenue = get_unit_revenue(line)

        total_demand += demand
        total_filled += filled
        fulfilled_revenue += unit_revenue * filled
        pallet_picks += pallet_count
        case_picks += loose_count

        line_rows.append(
            {
                "demand": demand,
                "filled": filled,
                "unit_revenue": unit_revenue,
            }
        )

    threshold_cases = math.ceil(
        FILL_THRESHOLD * total_demand - NUMERICAL_TOLERANCE
    )
    below_threshold = total_filled < threshold_cases

    shortfall_penalty = 0.0
    if below_threshold:
        for row_value in line_rows:
            shortfall_penalty += (
                PENALTY_RATE
                * row_value["unit_revenue"]
                * max(row_value["demand"] - row_value["filled"], 0.0)
            )

    shipping = (
        float(shipping_cost.get((dc, zip_code), 0.0))
        if total_filled > NUMERICAL_TOLERANCE
        else 0.0
    )

    return {
        "filled": total_filled,
        "demand": total_demand,
        "revenue": fulfilled_revenue,
        "penalty": shortfall_penalty,
        "shipping": shipping,
        "proxy_Z": fulfilled_revenue - shortfall_penalty - shipping,
        "case_picks": case_picks,
        "pallet_picks": pallet_picks,
        "served_proxy": float(total_filled > NUMERICAL_TOLERANCE),
    }

candidate_records = []

for order_id, lines in order.groupby("Group_Flag", sort=False):
    default_dc = lines["Plant"].iloc[0]
    pgi = lines["transportationplanningdate"].iloc[0]
    zip_code = lines["ZipCode"].iloc[0]
    demand = float(lines["OrderedQty_converted"].sum())

    default_metrics = option_proxy_metrics(default_dc, pgi, zip_code, lines)

    if default_metrics["filled"] >= demand - NUMERICAL_TOLERANCE:
        continue

    minimum_gain = max(0.05 * demand, 100.0)
    best_alternate = None

    for dc in all_dcs:
        if dc == default_dc:
            continue
        if (dc, zip_code) not in shipping_cost:
            continue
        if effective_order_capacity(dc, pgi) <= 0:
            continue
        if (
            case_pick_capacity.get((dc, pgi), 0.0) <= 0
            and pallet_pick_capacity.get((dc, pgi), 0.0) <= 0
        ):
            continue

        alternate_metrics = option_proxy_metrics(dc, pgi, zip_code, lines)
        fill_gain = alternate_metrics["filled"] - default_metrics["filled"]

        if fill_gain + NUMERICAL_TOLERANCE < minimum_gain:
            continue

        candidate = (dc, alternate_metrics)
        if best_alternate is None:
            best_alternate = candidate
        else:
            _, old_metrics = best_alternate
            if (
                alternate_metrics["filled"],
                alternate_metrics["proxy_Z"],
            ) > (
                old_metrics["filled"],
                old_metrics["proxy_Z"],
            ):
                best_alternate = candidate

    if best_alternate is None:
        continue

    alternate_dc, alternate_metrics = best_alternate

    total_order_revenue = float(lines["Order_SKU_Revenue"].sum())
    revenue_per_case = total_order_revenue / demand if demand > 0 else 0.0
    default_shortfall_value = (
        demand - default_metrics["filled"]
    ) * revenue_per_case
    diversion_value_gain = max(
        alternate_metrics["proxy_Z"] - default_metrics["proxy_Z"],
        0.0,
    )
    risk_score = default_shortfall_value + diversion_value_gain

    record = {
        "order_id": order_id,
        "default_dc": default_dc,
        "alt_dc": alternate_dc,
        "pgi": pgi,
        "zip": zip_code,
        "demand": demand,
        "risk_score": risk_score,
    }

    for prefix, metrics in [
        ("default", default_metrics),
        ("alt", alternate_metrics),
    ]:
        for key, value in metrics.items():
            record[f"{prefix}_{key}"] = value

    candidate_records.append(record)

candidates = pd.DataFrame(candidate_records)

# if candidates.empty:
#     raise ValueError(
#         "No divert-eligible candidates survived screening. "
#         "Check plant, date, ZIP, inventory, and capacity coverage."
#     )

candidates = candidates.sort_values(
    ["risk_score", "alt_proxy_Z", "alt_filled"],
    ascending=[False, False, False],
).reset_index(drop=True)

print("Divert-eligible orders:", len(candidates))
display(
    candidates[
        [
            "order_id", "default_dc", "alt_dc", "demand",
            "default_filled", "alt_filled",
            "default_proxy_Z", "alt_proxy_Z", "risk_score",
        ]
    ].head(15)
)

def build_contested_ranking(candidate_table):

    ranked = candidate_table.copy()
    group_keys = ["alt_dc", "pgi"]

    group_stats = (
        ranked.groupby(group_keys)
        .agg(
            competing_orders=("order_id", "count"),
            total_alt_case_picks=("alt_case_picks", "sum"),
            total_alt_pallet_picks=("alt_pallet_picks", "sum"),
            total_alt_served=("alt_served_proxy", "sum"),
        )
        .reset_index()
    )

    pressure_rows = []
    for _, group in group_stats.iterrows():
        key = (group["alt_dc"], group["pgi"])
        dock_cap = effective_order_capacity(*key)
        case_cap = float(case_pick_capacity.get(key, 0.0))
        pallet_cap = float(pallet_pick_capacity.get(key, 0.0))

        dock_pressure = group["total_alt_served"] / max(dock_cap, 1.0)
        case_pressure = group["total_alt_case_picks"] / max(case_cap, 1.0)
        pallet_pressure = group["total_alt_pallet_picks"] / max(pallet_cap, 1.0)

        pressure_rows.append(
            {
                "alt_dc": group["alt_dc"],
                "pgi": group["pgi"],
                "competing_orders": group["competing_orders"],
                "dock_pressure": dock_pressure,
                "case_pressure": case_pressure,
                "pallet_pressure": pallet_pressure,
                "resource_pressure": max(
                    dock_pressure,
                    case_pressure,
                    pallet_pressure,
                ),
            }
        )

    pressure_table = pd.DataFrame(pressure_rows)
    ranked = ranked.merge(
        pressure_table,
        on=group_keys,
        how="left",
    )

    ranked["contested_score"] = (
        ranked["resource_pressure"]
        * ranked["competing_orders"]
        * np.log1p(ranked["risk_score"].clip(lower=0.0))
    )

    return ranked.sort_values(
        [
            "contested_score",
            "resource_pressure",
            "competing_orders",
            "risk_score",
        ],
        ascending=[False, False, False, False],
    ).reset_index(drop=True)

def select_focus_batch(candidate_table, batch_size, mode):
    n_select = min(batch_size, len(candidate_table))

    if mode == "high_risk":
        selected = (
            candidate_table.sort_values(
                ["risk_score", "alt_proxy_Z", "alt_filled"],
                ascending=[False, False, False],
            )
            .head(n_select)
            .copy()
        )
    elif mode == "contested":
        ranked = build_contested_ranking(candidate_table)

        # Anchor on the single strongest shared alternate-DC/date conflict.
        leading_key = (
            ranked.iloc[0]["alt_dc"],
            ranked.iloc[0]["pgi"],
        )
        same_group = ranked[
            (ranked["alt_dc"] == leading_key[0])
            & (ranked["pgi"] == leading_key[1])
        ].copy()

        selected = same_group.head(n_select).copy()


        if len(selected) < n_select:
            remaining = ranked[
                ~ranked["order_id"].isin(selected["order_id"])
            ].head(n_select - len(selected))
            selected = pd.concat(
                [selected, remaining],
                ignore_index=True,
            )
    else:
        raise ValueError(
            "BATCH_MODE must be 'high_risk' or 'contested'."
        )

    return selected.reset_index(drop=True)

focus = select_focus_batch(
    candidates,
    BATCH_SIZE,
    BATCH_MODE,
)

N_MASTER_VARIABLES = len(focus)
order_ids = focus["order_id"].tolist()
focus_lines = order[
    order["Group_Flag"].isin(order_ids)
].copy()

if focus.empty:
    raise ValueError("The selected focus batch is empty.")

print(
    f"Selected {len(focus)} orders from {len(candidates)} candidates "
    f"using BATCH_MODE='{BATCH_MODE}'."
)

display_columns = [
    "order_id", "default_dc", "alt_dc", "pgi", "demand",
    "default_filled", "alt_filled",
    "default_proxy_Z", "alt_proxy_Z", "risk_score",
]
for optional_column in [
    "competing_orders",
    "resource_pressure",
    "contested_score",
]:
    if optional_column in focus.columns:
        display_columns.append(optional_column)

display(focus[display_columns])
print("Distinct SKUs:", focus_lines["MaterialNumber"].nunique())

def validate_bits(bits):
    bits = tuple(int(bit) for bit in bits)
    if len(bits) != len(order_ids):
        raise ValueError(
            f"Expected {len(order_ids)} bits but received {len(bits)}."
        )
    if any(bit not in (0, 1) for bit in bits):
        raise ValueError("Every decision must be 0 or 1.")
    return bits

def bits_to_assignment(bits):
    bits = validate_bits(bits)
    assignment = {}
    for index, row in focus.iterrows():
        assignment[row["order_id"]] = (
            row["alt_dc"] if bits[index] == 1 else row["default_dc"]
        )
    return assignment

def assignment_to_bits(assignment):
    bits = []
    for _, row in focus.iterrows():
        chosen_dc = assignment[row["order_id"]]
        if chosen_dc == row["default_dc"]:
            bits.append(0)
        elif chosen_dc == row["alt_dc"]:
            bits.append(1)
        else:
            raise ValueError(
                f"Order {row['order_id']} has an invalid assigned DC {chosen_dc}."
            )
    return tuple(bits)

def proxy_capacity_loads(values):

    dock_load = defaultdict(float)
    case_load = defaultdict(float)
    pallet_load = defaultdict(float)

    for index, row in focus.iterrows():
        diversion = float(values[index])
        stay = 1.0 - diversion

        default_key = (row["default_dc"], row["pgi"])
        alternate_key = (row["alt_dc"], row["pgi"])

        dock_load[default_key] += stay * row["default_served_proxy"]
        dock_load[alternate_key] += diversion * row["alt_served_proxy"]

        case_load[default_key] += stay * row["default_case_picks"]
        case_load[alternate_key] += diversion * row["alt_case_picks"]

        pallet_load[default_key] += stay * row["default_pallet_picks"]
        pallet_load[alternate_key] += diversion * row["alt_pallet_picks"]

    return dock_load, case_load, pallet_load

def safe_name(value):
    return re.sub(r"[^A-Za-z0-9_]+", "_", str(value))

recourse_cache = {}

def solve_recourse(bits, verbose=False, use_cache=True):
    bits = validate_bits(bits)

    if use_cache and not verbose and bits in recourse_cache:
        return recourse_cache[bits]

    assignment = bits_to_assignment(bits)
    model = pulp.LpProblem("DOM_recourse", pulp.LpMaximize)

    x = {}
    pallets = {}
    loose = {}
    shortfall = {}
    served = {}
    below_threshold = {}

    inventory_usage = defaultdict(list)
    dock_usage = defaultdict(list)
    case_pick_usage = defaultdict(list)
    pallet_pick_usage = defaultdict(list)

    revenue_terms = []
    penalty_terms = []
    shipping_terms = []

    line_metadata = {}
    order_metadata = {}

    for _, focus_row in focus.iterrows():
        order_id = focus_row["order_id"]
        dc = assignment[order_id]
        pgi = focus_row["pgi"]
        zip_code = focus_row["zip"]
        lines = focus_lines[focus_lines["Group_Flag"] == order_id]

        order_safe = safe_name(order_id)
        line_keys = []
        total_demand = 0

        for line_index, line in lines.iterrows():
            demand_value = float(line["OrderedQty_converted"])
            demand_quantity = int(round(demand_value))

            if abs(demand_value - demand_quantity) > NUMERICAL_TOLERANCE:
                raise ValueError(
                    f"Order {order_id}, line {line_index} has non-integer "
                    f"case demand {demand_value}."
                )
            if demand_quantity <= 0:
                continue

            cpp = cases_per_pallet(line)
            line_safe = safe_name(line_index)
            key = (order_id, line_index)

            x[key] = pulp.LpVariable(
                f"x_{order_safe}_{line_safe}",
                lowBound=0,
                upBound=demand_quantity,
                cat="Integer",
            )
            pallets[key] = pulp.LpVariable(
                f"pallet_{order_safe}_{line_safe}",
                lowBound=0,
                upBound=demand_quantity // cpp,
                cat="Integer",
            )
            loose[key] = pulp.LpVariable(
                f"loose_{order_safe}_{line_safe}",
                lowBound=0,
                upBound=max(cpp - 1, 0),
                cat="Integer",
            )
            shortfall[key] = pulp.LpVariable(
                f"shortfall_{order_safe}_{line_safe}",
                lowBound=0,
                upBound=demand_quantity,
                cat="Integer",
            )

            model += x[key] == cpp * pallets[key] + loose[key]

            inventory_usage[
                (dc, line["MaterialNumber"], pgi)
            ].append(x[key])
            case_pick_usage[(dc, pgi)].append(loose[key])
            pallet_pick_usage[(dc, pgi)].append(pallets[key])

            unit_revenue = get_unit_revenue(line)
            revenue_terms.append(unit_revenue * x[key])

            line_keys.append(key)
            total_demand += demand_quantity

            line_metadata[key] = {
                "order_id": order_id,
                "line_index": line_index,
                "sku": line["MaterialNumber"],
                "dc": dc,
                "pgi": pgi,
                "demand": demand_quantity,
                "cpp": cpp,
                "unit_revenue": unit_revenue,
            }

        if total_demand <= 0:
            raise ValueError(f"Order {order_id} has no positive demand.")

        served[order_id] = pulp.LpVariable(
            f"served_{order_safe}", cat="Binary"
        )
        below_threshold[order_id] = pulp.LpVariable(
            f"below_threshold_{order_safe}", cat="Binary"
        )

        total_filled = pulp.lpSum(x[key] for key in line_keys)
        threshold_cases = int(
            math.ceil(
                FILL_THRESHOLD * total_demand - NUMERICAL_TOLERANCE
            )
        )

        model += total_filled <= total_demand * served[order_id]
        model += total_filled >= served[order_id]

        model += (
            total_filled
            >= threshold_cases * (1 - below_threshold[order_id])
        )
        model += (
            total_filled
            <= threshold_cases - 1
            + total_demand * (1 - below_threshold[order_id])
        )

        for key in line_keys:
            demand_quantity = line_metadata[key]["demand"]
            unit_revenue = line_metadata[key]["unit_revenue"]

            model += (
                shortfall[key]
                <= demand_quantity * below_threshold[order_id]
            )
            model += shortfall[key] <= demand_quantity - x[key]
            model += (
                shortfall[key]
                >= demand_quantity - x[key]
                - demand_quantity * (1 - below_threshold[order_id])
            )

            penalty_terms.append(
                PENALTY_RATE * unit_revenue * shortfall[key]
            )

        dock_usage[(dc, pgi)].append(served[order_id])

        shipping_value = float(
            shipping_cost.get((dc, zip_code), 0.0)
        )
        shipping_terms.append(shipping_value * served[order_id])

        order_metadata[order_id] = {
            "dc": dc,
            "pgi": pgi,
            "zip": zip_code,
            "demand": total_demand,
            "line_keys": line_keys,
            "shipping_cost": shipping_value,
        }

    for resource_key, variables in inventory_usage.items():
        model += (
            pulp.lpSum(variables)
            <= float(inventory.get(resource_key, 0.0))
        )

    for resource_key, variables in dock_usage.items():
        model += (
            pulp.lpSum(variables)
            <= effective_order_capacity(*resource_key)
        )

    for resource_key, variables in case_pick_usage.items():
        model += (
            pulp.lpSum(variables)
            <= float(case_pick_capacity.get(resource_key, 0.0))
        )

    for resource_key, variables in pallet_pick_usage.items():
        model += (
            pulp.lpSum(variables)
            <= float(pallet_pick_capacity.get(resource_key, 0.0))
        )

    model += (
        pulp.lpSum(revenue_terms)
        - pulp.lpSum(penalty_terms)
        - pulp.lpSum(shipping_terms)
    )

    status_code = model.solve(pulp.PULP_CBC_CMD(msg=0))
    status_name = pulp.LpStatus[status_code]

    if status_name != "Optimal":
        raise RuntimeError(
            f"Recourse returned {status_name} for bits {bits}."
        )

    x_value = {
        key: float(variable.value() or 0.0)
        for key, variable in x.items()
    }
    pallet_value = {
        key: float(variable.value() or 0.0)
        for key, variable in pallets.items()
    }
    loose_value = {
        key: float(variable.value() or 0.0)
        for key, variable in loose.items()
    }
    shortfall_value = {
        key: float(variable.value() or 0.0)
        for key, variable in shortfall.items()
    }
    served_value = {
        order_id: int(round(variable.value() or 0.0))
        for order_id, variable in served.items()
    }
    threshold_value = {
        order_id: int(round(variable.value() or 0.0))
        for order_id, variable in below_threshold.items()
    }

    total_revenue = 0.0
    total_penalty = 0.0
    total_shipping = 0.0
    order_detail = []
    line_detail = []

    for order_id, metadata in order_metadata.items():
        order_filled = 0.0
        order_revenue = 0.0
        order_penalty = 0.0
        order_case_picks = 0.0
        order_pallet_picks = 0.0
        order_shortfall = 0.0

        for key in metadata["line_keys"]:
            info = line_metadata[key]
            filled = x_value[key]
            line_revenue = info["unit_revenue"] * filled
            line_penalty = (
                PENALTY_RATE
                * info["unit_revenue"]
                * shortfall_value[key]
            )

            order_filled += filled
            order_revenue += line_revenue
            order_penalty += line_penalty
            order_case_picks += loose_value[key]
            order_pallet_picks += pallet_value[key]
            order_shortfall += shortfall_value[key]

            line_detail.append(
                {
                    **info,
                    "filled": filled,
                    "pallets": pallet_value[key],
                    "loose_cases": loose_value[key],
                    "shortfall_cases": shortfall_value[key],
                    "revenue": line_revenue,
                    "penalty": line_penalty,
                }
            )

        order_shipping = (
            metadata["shipping_cost"]
            if served_value[order_id] == 1
            else 0.0
        )

        total_revenue += order_revenue
        total_penalty += order_penalty
        total_shipping += order_shipping

        order_detail.append(
            {
                "order_id": order_id,
                "dc": metadata["dc"],
                "pgi": metadata["pgi"],
                "filled": order_filled,
                "demand": metadata["demand"],
                "fill_rate": order_filled / metadata["demand"],
                "served": served_value[order_id],
                "below_threshold": threshold_value[order_id],
                "shortfall_cases": order_shortfall,
                "revenue": order_revenue,
                "penalty": order_penalty,
                "shipping": order_shipping,
                "case_picks": order_case_picks,
                "pallet_picks": order_pallet_picks,
            }
        )

    objective_value = total_revenue - total_penalty - total_shipping
    solver_objective = float(pulp.value(model.objective))

    if not np.isclose(
        objective_value,
        solver_objective,
        atol=1e-3,
        rtol=1e-7,
    ):
        raise RuntimeError(
            f"Reconstructed Z={objective_value} differs from "
            f"solver Z={solver_objective}."
        )

    result = {
        "bits": bits,
        "assignment": assignment,
        "Z": objective_value,
        "revenue": total_revenue,
        "penalty": total_penalty,
        "shipping": total_shipping,
        "order_detail": order_detail,
        "line_detail": line_detail,
        "status": status_name,
    }

    if use_cache and not verbose:
        recourse_cache[bits] = result

    if verbose:
        display(pd.DataFrame(order_detail))
        display(pd.DataFrame(line_detail))

    return result


def summarize_result(name, result, runtime_seconds):
    detail = result["order_detail"]
    total_filled = sum(row["filled"] for row in detail)
    total_demand = sum(row["demand"] for row in detail)
    fill_rate = total_filled / total_demand if total_demand > 0 else 0.0

    return {
        "method": name,
        "Z": result["Z"],
        "fill_rate": fill_rate,
        "reassigned_orders": sum(result["bits"]),
        "revenue": result["revenue"],
        "penalty": result["penalty"],
        "shipping": result["shipping"],
        "runtime_s": runtime_seconds,
        "bits": "".join(map(str, result["bits"])),
    }

# -------------------------- Default baseline --------------------------
recourse_cache.clear()
start = time.perf_counter()
default_bits = tuple(0 for _ in order_ids)
default_result = solve_recourse(default_bits)
t_default = time.perf_counter() - start

# --------------------------- Greedy baseline --------------------------
recourse_cache.clear()
start = time.perf_counter()
greedy_bits = list(default_bits)
greedy_variable_order = list(
    focus.sort_values("risk_score", ascending=False).index
)

for variable_index in greedy_variable_order:
    current_result = solve_recourse(tuple(greedy_bits))
    trial_bits = greedy_bits.copy()
    trial_bits[variable_index] = 1 - trial_bits[variable_index]
    trial_result = solve_recourse(tuple(trial_bits))

    if trial_result["Z"] > current_result["Z"] + NUMERICAL_TOLERANCE:
        greedy_bits = trial_bits

greedy_result = solve_recourse(tuple(greedy_bits))
t_greedy = time.perf_counter() - start

# --------------------------- Exact benchmark -------------------------
exact_result = None
t_exact = np.nan

if len(order_ids) <= EXACT_ENUMERATION_LIMIT:
    recourse_cache.clear()
    start = time.perf_counter()
    best_exact = None

    for mask in range(2 ** len(order_ids)):
        bits = tuple(
            (mask >> variable_index) & 1
            for variable_index in range(len(order_ids))
        )
        result = solve_recourse(bits)

        if (
            best_exact is None
            or result["Z"] > best_exact["Z"] + NUMERICAL_TOLERANCE
        ):
            best_exact = result

    exact_result = best_exact
    t_exact = time.perf_counter() - start
else:
    print(
        f"Exact enumeration skipped: {len(order_ids)} variables exceed "
        f"the limit {EXACT_ENUMERATION_LIMIT}."
    )

print(f"Default Z: {default_result['Z']:,.2f}")
print(f"Greedy  Z: {greedy_result['Z']:,.2f}")
if exact_result is not None:
    print(f"Exact   Z: {exact_result['Z']:,.2f}")
#     if len(set(exact_result["bits"])) == 1:
#         print(
#             "WARNING: the exact optimum is an all-equal bitstring. "
#             "For a stronger optimization case, rerun with the other BATCH_MODE."
#         )

# print(
#     "The hybrid stage below clears the exact-enumeration cache before its "
#     "own timing starts, for the same fairness reason as above."
# )


def minimum_pce_qubits(n_variables, degree=2):
    if degree != 2:
        raise NotImplementedError(
            "This notebook only implements degree-2 PCE."
        )
    if n_variables <= 0:
        raise ValueError("At least one variable is required.")

    n_qubits = 2
    while 3 * math.comb(n_qubits, 2) < n_variables:
        n_qubits += 1
    return n_qubits

def pair_pauli_label(n_qubits, qubit_i, qubit_j, axis):
    chars = ["I"] * n_qubits
    chars[n_qubits - 1 - qubit_i] = axis
    chars[n_qubits - 1 - qubit_j] = axis
    return "".join(chars)

N_QUBITS = minimum_pce_qubits(
    N_MASTER_VARIABLES,
    PCE_DEGREE,
)

all_correlators = []
for axis in ["X", "Y", "Z"]:
    for qubit_i, qubit_j in combinations(range(N_QUBITS), 2):
        label = pair_pauli_label(
            N_QUBITS,
            qubit_i,
            qubit_j,
            axis,
        )
        all_correlators.append(
            {
                "axis": axis,
                "qubit_i": qubit_i,
                "qubit_j": qubit_j,
                "label": label,
                "operator": SparsePauliOp.from_list([(label, 1.0)]),
            }
        )

selected_correlators = all_correlators[:N_MASTER_VARIABLES]
PCE_OBSERVABLES = [
    correlator["operator"]
    for correlator in selected_correlators
]

mapping_rows = []
for variable_index, (order_id, correlator) in enumerate(
    zip(order_ids, selected_correlators)
):
    mapping_rows.append(
        {
            "variable_index": variable_index,
            "order_id": order_id,
            "decision": "0=default, 1=alternate",
            "axis_group": correlator["axis"],
            "qubits": (
                f"({correlator['qubit_i']},"
                f"{correlator['qubit_j']})"
            ),
            "Pauli_label": correlator["label"],
        }
    )

pce_mapping = pd.DataFrame(mapping_rows)

ansatz = efficient_su2(
    num_qubits=N_QUBITS,
    reps=ANSATZ_REPS,
    entanglement="full",
)
estimator = AerEstimator()

def correlator_values(
    theta,
    estimator_object=estimator,
    circuit=ansatz,
    observables=PCE_OBSERVABLES,
):
    publication = (
        circuit,
        observables,
        np.asarray(theta, dtype=float),
    )
    result = estimator_object.run([publication]).result()[0]
    values = np.asarray(result.data.evs)
    values = np.real_if_close(values).astype(float).reshape(-1)

    if len(values) != N_MASTER_VARIABLES:
        raise RuntimeError(
            f"Expected {N_MASTER_VARIABLES} correlations, "
            f"received {len(values)}."
        )

    return values

def soft_bits_from_correlations(correlations, alpha):
    correlations = np.asarray(correlations, dtype=float)
    return (
        1.0 - np.tanh(alpha * correlations)
    ) / 2.0

def hard_bits_from_correlations(correlations):
    correlations = np.asarray(correlations, dtype=float)
    return tuple(
        int(value < 0.0)
        for value in correlations
    )

print("Master variables:", N_MASTER_VARIABLES)
print("Direct encoding qubits:", N_MASTER_VARIABLES)
print("Compressed PCE qubits:", N_QUBITS)
print(
    "Available two-body correlators:",
    3 * math.comb(N_QUBITS, 2),
)
print("Ansatz parameters:", ansatz.num_parameters)
display(pce_mapping)


all_proxy_values = np.concatenate(
    [
        focus["default_proxy_Z"].to_numpy(dtype=float),
        focus["alt_proxy_Z"].to_numpy(dtype=float),
    ]
)
OBJECTIVE_SCALE = max(
    float(np.max(np.abs(all_proxy_values))),
    1.0,
)

def expected_proxy_value(soft_bits):
    total = 0.0

    for index, row in focus.iterrows():
        diversion = float(soft_bits[index])
        total += (
            (1.0 - diversion) * float(row["default_proxy_Z"])
            + diversion * float(row["alt_proxy_Z"])
        )

    return total

def normalized_capacity_violations(soft_bits):
    dock_load, case_load, pallet_load = proxy_capacity_loads(
        soft_bits
    )

    dock_violation = {}
    case_violation = {}
    pallet_violation = {}

    for key, used in dock_load.items():
        capacity = effective_order_capacity(*key)
        excess = max(0.0, used - capacity)
        dock_violation[key] = excess / max(capacity, 1.0)

    for key, used in case_load.items():
        capacity = float(case_pick_capacity.get(key, 0.0))
        excess = max(0.0, used - capacity)
        case_violation[key] = excess / max(capacity, 1.0)

    for key, used in pallet_load.items():
        capacity = float(pallet_pick_capacity.get(key, 0.0))
        excess = max(0.0, used - capacity)
        pallet_violation[key] = excess / max(capacity, 1.0)

    return (
        dock_violation,
        case_violation,
        pallet_violation,
    )

def augmented_lagrangian_penalty(
    violations,
    multipliers,
    mu,
):
    total = 0.0

    for key, violation in violations.items():
        multiplier = float(multipliers.get(key, 0.0))
        total += (
            multiplier * violation
            + 0.5 * mu * violation**2
        )

    return total

def master_loss(
    theta,
    alpha,
    dock_multipliers,
    case_multipliers,
    pallet_multipliers,
):
    correlations = correlator_values(theta)
    soft_bits = soft_bits_from_correlations(
        correlations,
        alpha,
    )

    normalized_value_term = (
        -expected_proxy_value(soft_bits)
        / OBJECTIVE_SCALE
    )

    dock_v, case_v, pallet_v = (
        normalized_capacity_violations(soft_bits)
    )

    capacity_term = (
        augmented_lagrangian_penalty(
            dock_v,
            dock_multipliers,
            AL_MU_DOCK,
        )
        + augmented_lagrangian_penalty(
            case_v,
            case_multipliers,
            AL_MU_CASE,
        )
        + augmented_lagrangian_penalty(
            pallet_v,
            pallet_multipliers,
            AL_MU_PALLET,
        )
    )

    return normalized_value_term + capacity_term

print("Objective normalization scale:", OBJECTIVE_SCALE)


from scipy.optimize import minimize

def update_multipliers(multipliers, violations, mu):
    for key, violation in violations.items():
        multipliers[key] = max(
            0.0,
            float(multipliers.get(key, 0.0))
            + mu * float(violation),
        )

def maximum_violation(*violation_dictionaries):
    values = [
        float(value)
        for dictionary in violation_dictionaries
        for value in dictionary.values()
    ]
    return max(values, default=0.0)

def run_single_pce_restart(restart_index, seed):
    rng = np.random.default_rng(seed)
    theta = rng.uniform(
        -np.pi,
        np.pi,
        size=ansatz.num_parameters,
    )

    alpha_initial = (
        ALPHA_C
        * N_QUBITS ** (PCE_DEGREE / 2)
    )
    alpha = float(alpha_initial)

    dock_multipliers = defaultdict(float)
    case_multipliers = defaultdict(float)
    pallet_multipliers = defaultdict(float)

    best_record = None
    history_rows = []
    seen_bits = set()
    stall = 0

    for outer in range(1, N_OUTER + 1):
        alpha_used = alpha

        optimization = minimize(
            lambda parameters: master_loss(
                parameters,
                alpha_used,
                dock_multipliers,
                case_multipliers,
                pallet_multipliers,
            ),
            theta,
            method="COBYLA",
            options={
                "maxiter": COBYLA_MAXITER,
                "tol": COBYLA_TOL,
            },
        )

        theta = np.asarray(
            optimization.x,
            dtype=float,
        )

        correlations = correlator_values(theta)
        soft_bits = soft_bits_from_correlations(
            correlations,
            alpha_used,
        )
        bits = hard_bits_from_correlations(correlations)
        recourse = solve_recourse(bits)

        dock_v, case_v, pallet_v = (
            normalized_capacity_violations(soft_bits)
        )
        max_violation = maximum_violation(
            dock_v,
            case_v,
            pallet_v,
        )

        new_best = (
            best_record is None
            or recourse["Z"]
            > best_record["recourse"]["Z"]
            + NUMERICAL_TOLERANCE
        )

        if new_best:
            best_record = {
                "restart": restart_index,
                "seed": seed,
                "outer": outer,
                "theta": theta.copy(),
                "alpha": alpha_used,
                "alpha_initial": alpha_initial,
                "correlations": correlations.copy(),
                "soft_bits": soft_bits.copy(),
                "bits": bits,
                "recourse": recourse,
                "master_loss": float(optimization.fun),
            }
            stall = 0
        else:
            stall += 1

        repeated = bits in seen_bits
        seen_bits.add(bits)

        history_rows.append(
            {
                "restart": restart_index,
                "seed": seed,
                "outer": outer,
                "alpha": alpha_used,
                "master_loss": float(optimization.fun),
                "recourse_Z": recourse["Z"],
                "incumbent_Z": best_record["recourse"]["Z"],
                "max_normalized_violation": max_violation,
                "bits": "".join(map(str, bits)),
                "repeated_bits": repeated,
                "optimizer_success": bool(
                    optimization.success
                ),
                "optimizer_message": str(
                    optimization.message
                ),
                "function_evaluations": int(
                    optimization.nfev
                ),
            }
        )

        update_multipliers(
            dock_multipliers,
            dock_v,
            AL_MU_DOCK,
        )
        update_multipliers(
            case_multipliers,
            case_v,
            AL_MU_CASE,
        )
        update_multipliers(
            pallet_multipliers,
            pallet_v,
            AL_MU_PALLET,
        )

        if stall >= PATIENCE:
            break

        alpha *= ALPHA_GROWTH

        if repeated:
            theta = theta + rng.normal(
                0.0,
                0.03,
                size=theta.shape,
            )

    return best_record, pd.DataFrame(history_rows)

# Fair timing: don't reuse any exact/greedy/default recourse evaluations.
recourse_cache.clear()
hybrid_start = time.perf_counter()

restart_best_records = []
restart_histories = []

for restart_index in range(N_RESTARTS):
    restart_seed = SEED + 1000 * restart_index
    best_record, history = run_single_pce_restart(
        restart_index,
        restart_seed,
    )
    restart_best_records.append(best_record)
    restart_histories.append(history)

pce_history = pd.concat(
    restart_histories,
    ignore_index=True,
)

best_pce_record = max(
    restart_best_records,
    key=lambda record: record["recourse"]["Z"],
)

pce_raw_result = best_pce_record["recourse"]

print("Best restart:", best_pce_record["restart"])
print("Best outer iteration:", best_pce_record["outer"])
print("Initial alpha:", best_pce_record["alpha_initial"])
print("Alpha used by best candidate:", best_pce_record["alpha"])
print("Raw decoded bits:", best_pce_record["bits"])
print("Raw PCE recourse Z:", f"{pce_raw_result['Z']:,.2f}")
display(pce_history)



#########################################
def complement_bits(bits):
    return tuple(
        1 - bit
        for bit in validate_bits(bits)
    )

def one_flip_postprocess(initial_bits):
    current_bits = validate_bits(initial_bits)
    current_result = solve_recourse(current_bits)

    trace = [
        {
            "step": 0,
            "move": "initial quantum decode",
            "bits": "".join(map(str, current_bits)),
            "Z": current_result["Z"],
        }
    ]

    complemented = complement_bits(current_bits)
    complement_result = solve_recourse(complemented)

    if (
        complement_result["Z"]
        > current_result["Z"] + NUMERICAL_TOLERANCE
    ):
        current_bits = complemented
        current_result = complement_result
        trace.append(
            {
                "step": len(trace),
                "move": "full complement",
                "bits": "".join(map(str, current_bits)),
                "Z": current_result["Z"],
            }
        )

    improved = True

    while improved:
        improved = False
        best_neighbor_bits = current_bits
        best_neighbor_result = current_result
        best_flip = None

        for variable_index in range(len(current_bits)):
            trial = list(current_bits)
            trial[variable_index] = (
                1 - trial[variable_index]
            )
            trial = tuple(trial)
            trial_result = solve_recourse(trial)

            if (
                trial_result["Z"]
                > best_neighbor_result["Z"]
                + NUMERICAL_TOLERANCE
            ):
                best_neighbor_bits = trial
                best_neighbor_result = trial_result
                best_flip = variable_index

        if best_flip is not None:
            current_bits = best_neighbor_bits
            current_result = best_neighbor_result
            improved = True

            trace.append(
                {
                    "step": len(trace),
                    "move": (
                        f"flip variable {best_flip} "
                        f"(order {order_ids[best_flip]})"
                    ),
                    "bits": "".join(map(str, current_bits)),
                    "Z": current_result["Z"],
                }
            )

    return current_result, pd.DataFrame(trace)

hybrid_result, postprocess_trace = (
    one_flip_postprocess(best_pce_record["bits"])
)

t_hybrid = time.perf_counter() - hybrid_start

print("Raw PCE Z:", f"{pce_raw_result['Z']:,.2f}")
print("Post-processed hybrid Z:", f"{hybrid_result['Z']:,.2f}")
print("Final bits:", hybrid_result["bits"])
print("Complete hybrid runtime:", f"{t_hybrid:.3f} seconds")
display(postprocess_trace)



####################################
comparison_rows = [
    summarize_result(
        "Default assignment",
        default_result,
        t_default,
    ),
    summarize_result(
        "Greedy reassignment",
        greedy_result,
        t_greedy,
    ),
]

if exact_result is not None:
    comparison_rows.append(
        summarize_result(
            "Exact benchmark",
            exact_result,
            t_exact,
        )
    )

comparison_rows.append(
    summarize_result(
        "Hybrid Quantum Method",
        hybrid_result,
        t_hybrid,
    )
)

comparison = pd.DataFrame(comparison_rows)

if (
    exact_result is not None
    and abs(exact_result["Z"]) > NUMERICAL_TOLERANCE
):
    comparison["gap_to_exact_pct"] = (
        100.0
        * (exact_result["Z"] - comparison["Z"])
        / abs(exact_result["Z"])
    )
else:
    comparison["gap_to_exact_pct"] = np.nan

comparison["fill_rate_pct"] = (
    100.0 * comparison["fill_rate"]
)
comparison["direct_qubits"] = N_MASTER_VARIABLES
comparison["compressed_pce_qubits"] = N_QUBITS
comparison["batch_mode"] = BATCH_MODE

display(
    comparison[
        [
            "method", "Z", "gap_to_exact_pct",
            "fill_rate_pct", "reassigned_orders",
            "revenue", "penalty", "shipping",
            "runtime_s", "bits",
            "direct_qubits", "compressed_pce_qubits", "batch_mode",
        ]
    ]
)

hybrid_detail = pd.DataFrame(
    hybrid_result["order_detail"]
)

recommendation_rows = []

for _, row in focus.iterrows():
    order_id = row["order_id"]
    detail = hybrid_detail[
        hybrid_detail["order_id"] == order_id
    ].iloc[0]
    chosen_dc = hybrid_result["assignment"][order_id]

    decision = (
        "KEEP_DEFAULT"
        if chosen_dc == row["default_dc"]
        else "DIVERT"
    )

    recommendation_rows.append(
        {
            "OrderID": order_id,
            "DefaultDC": row["default_dc"],
            "AlternateDC": row["alt_dc"],
            "RecommendedDC": chosen_dc,
            "Decision": decision,
            "OrderedCases": detail["demand"],
            "FilledCases": detail["filled"],
            "FillRatePct": 100.0 * detail["fill_rate"],
            "BelowThreshold": bool(
                detail["below_threshold"]
            ),
            "ShortfallCases": detail["shortfall_cases"],
            "Revenue": detail["revenue"],
            "Penalty": detail["penalty"],
            "Shipping": detail["shipping"],
            "CasePicks": detail["case_picks"],
            "PalletPicks": detail["pallet_picks"],
        }
    )

recommendations = pd.DataFrame(
    recommendation_rows
)
display(recommendations)

plt.figure(figsize=(8, 4))
plt.bar(comparison["method"], comparison["Z"])
plt.ylabel("Business objective Z")
plt.title("Classical and hybrid objective comparison")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

#####################################################
diagnostic_rows = []

for variable_index, mapping in pce_mapping.iterrows():
    raw_bit = best_pce_record["bits"][variable_index]
    final_bit = hybrid_result["bits"][variable_index]

    diagnostic_rows.append(
        {
            **mapping.to_dict(),
            "correlation": (
                best_pce_record["correlations"][
                    variable_index
                ]
            ),
            "absolute_margin": abs(
                best_pce_record["correlations"][
                    variable_index
                ]
            ),
            "soft_diversion_value": (
                best_pce_record["soft_bits"][
                    variable_index
                ]
            ),
            "raw_quantum_bit": raw_bit,
            "final_postprocessed_bit": final_bit,
            "changed_by_postprocessing": (
                raw_bit != final_bit
            ),
        }
    )

pce_diagnostics = pd.DataFrame(
    diagnostic_rows
)
display(pce_diagnostics)

####################################################
from qiskit import transpile
from qiskit_aer.noise import NoiseModel
from qiskit_aer.primitives import Estimator as AerEstimatorV1

noise_trial_rows = []
noise_summary_rows = []

try:
    fake_backend = None
    fake_backend_name = None

    try:
        from qiskit_ibm_runtime.fake_provider import FakeManilaV2
        fake_backend = FakeManilaV2()
        fake_backend_name = "FakeManilaV2"
    except Exception:
        try:
            from qiskit_ibm_runtime.fake_provider import FakeLimaV2
            fake_backend = FakeLimaV2()
            fake_backend_name = "FakeLimaV2"
        except Exception:
            fake_backend = None

    if fake_backend is None:
        raise RuntimeError(
            "No compatible small IBM fake backend was found."
        )

    if N_QUBITS > fake_backend.num_qubits:
        raise RuntimeError(
            f"Backend has {fake_backend.num_qubits} qubits, "
            f"but PCE needs {N_QUBITS}."
        )

    transpiled_ansatz = transpile(
        ansatz,
        backend=fake_backend,
        initial_layout=list(range(N_QUBITS)),
        optimization_level=1,
        seed_transpiler=SEED,
    )

    mapped_observables = [
        observable.apply_layout(transpiled_ansatz.layout)
        for observable in PCE_OBSERVABLES
    ]

    noise_model = NoiseModel.from_backend(fake_backend)
    clean_bits = best_pce_record["bits"]

    for trial in range(NOISE_TRIALS):
        trial_seed = SEED + 10_000 + trial

        noisy_estimator = AerEstimatorV1(
            backend_options={
                "noise_model": noise_model,
                "seed_simulator": trial_seed,
            },
            run_options={
                "shots": NOISE_SHOTS,
                "seed": trial_seed,
            },
            skip_transpilation=True,
        )

        repeated_circuits = [
            transpiled_ansatz
            for _ in PCE_OBSERVABLES
        ]
        repeated_parameters = [
            np.asarray(best_pce_record["theta"], dtype=float)
            for _ in PCE_OBSERVABLES
        ]

        estimator_result = noisy_estimator.run(
            repeated_circuits,
            mapped_observables,
            repeated_parameters,
        ).result()

        noisy_correlations = np.asarray(
            estimator_result.values,
            dtype=float,
        )
        noisy_bits = hard_bits_from_correlations(
            noisy_correlations
        )

        noisy_raw_result = solve_recourse(noisy_bits)
        noisy_repaired_result, _ = one_flip_postprocess(
            noisy_bits
        )

        bit_flips = sum(
            int(clean != noisy)
            for clean, noisy in zip(
                clean_bits,
                noisy_bits,
            )
        )

        noise_trial_rows.append(
            {
                "trial": trial,
                "seed": trial_seed,
                "noise_model": fake_backend_name,
                "shots": NOISE_SHOTS,
                "raw_noisy_bits": "".join(map(str, noisy_bits)),
                "bit_flips_vs_noiseless": bit_flips,
                "exact_bitstring_survived": bit_flips == 0,
                "minimum_correlation_margin": float(
                    np.min(np.abs(noisy_correlations))
                ),
                "raw_noisy_Z": noisy_raw_result["Z"],
                "repaired_noisy_Z": noisy_repaired_result["Z"],
                "gap_after_repair": (
                    hybrid_result["Z"]
                    - noisy_repaired_result["Z"]
                ),
            }
        )

    noise_trials = pd.DataFrame(noise_trial_rows)

    noise_summary_rows.append(
        {
            "noise_model": fake_backend_name,
            "status": "completed",
            "trials": NOISE_TRIALS,
            "shots_per_trial": NOISE_SHOTS,
            "bitstring_survival_rate": float(
                noise_trials["exact_bitstring_survived"].mean()
            ),
            "mean_bit_flips": float(
                noise_trials["bit_flips_vs_noiseless"].mean()
            ),
            "max_bit_flips": int(
                noise_trials["bit_flips_vs_noiseless"].max()
            ),
            "minimum_observed_margin": float(
                noise_trials["minimum_correlation_margin"].min()
            ),
            "mean_raw_noisy_Z": float(
                noise_trials["raw_noisy_Z"].mean()
            ),
            "std_raw_noisy_Z": float(
                noise_trials["raw_noisy_Z"].std(ddof=1)
            ),
            "mean_repaired_noisy_Z": float(
                noise_trials["repaired_noisy_Z"].mean()
            ),
            "std_repaired_noisy_Z": float(
                noise_trials["repaired_noisy_Z"].std(ddof=1)
            ),
            "feasible_repaired_rate": 1.0,
        }
    )

    display(noise_trials)
except Exception as error:
    noise_trials = pd.DataFrame()
    noise_summary_rows.append(
        {
            "noise_model": None,
            "status": f"skipped: {error}",
            "trials": 0,
            "shots_per_trial": NOISE_SHOTS,
            "bitstring_survival_rate": np.nan,
            "mean_bit_flips": np.nan,
            "max_bit_flips": np.nan,
            "minimum_observed_margin": np.nan,
            "mean_raw_noisy_Z": np.nan,
            "std_raw_noisy_Z": np.nan,
            "mean_repaired_noisy_Z": np.nan,
            "std_repaired_noisy_Z": np.nan,
            "feasible_repaired_rate": np.nan,
        }
    )
    print("Noise analysis skipped:", error)

noise_diagnostics = pd.DataFrame(
    noise_summary_rows
)
display(noise_diagnostics)

########################################################

final_recommendations = recommendations[
    [
        "OrderID",
        "DefaultDC",
        "AlternateDC",
        "RecommendedDC",
        "Decision",
        "OrderedCases",
        "FilledCases",
        "FillRatePct",
        "BelowThreshold",
        "ShortfallCases",
    ]
].copy()

# Round operational numbers for cleaner presentation
for column in [
    "OrderedCases",
    "FilledCases",
    "FillRatePct",
    "ShortfallCases",
]:
    final_recommendations[column] = (
        final_recommendations[column]
        .astype(float)
        .round(1)
    )

print("Final planner recommendations:")
display(final_recommendations)

###############################################
readiness_checks = []

def add_readiness_check(name, passed, evidence, required=True):
    readiness_checks.append(
        {
            "check": name,
            "passed": bool(passed),
            "required": bool(required),
            "evidence": evidence,
        }
    )

add_readiness_check(
    "Exact benchmark available",
    exact_result is not None,
    (
        f"Exact Z={exact_result['Z']:,.2f}"
        if exact_result is not None
        else "Exact enumeration was skipped."
    ),
)

if exact_result is not None:
    optimality_gap = (
        100.0
        * (exact_result["Z"] - hybrid_result["Z"])
        / max(abs(exact_result["Z"]), 1.0)
    )
    add_readiness_check(
        "Hybrid gap is at most 1%",
        optimality_gap <= 1.0 + NUMERICAL_TOLERANCE,
        f"Gap={optimality_gap:.6f}%",
    )
    add_readiness_check(
        "Optimization instance has a mixed optimum",
        len(set(exact_result["bits"])) > 1,
        f"Exact bits={''.join(map(str, exact_result['bits']))}",
        required=False,
    )

add_readiness_check(
    "COBYLA formal success observed",
    bool(pce_history["optimizer_success"].any()),
    (
        "At least one restart terminated successfully."
        if pce_history["optimizer_success"].any()
        else "All restarts were budget-limited; disclose this."
    ),
    required=False,
)

noise_completed = (
    not noise_diagnostics.empty
    and noise_diagnostics.iloc[0]["status"] == "completed"
)
add_readiness_check(
    "Repeated noise study completed",
    noise_completed,
    (
        f"{NOISE_TRIALS} trials at {NOISE_SHOTS} shots"
        if noise_completed
        else str(noise_diagnostics.iloc[0]["status"])
    ),
)

add_readiness_check(
    "Planner recommendations table created",
    not final_recommendations.empty,
    f"{len(final_recommendations)} recommendations",
)

submission_readiness = pd.DataFrame(readiness_checks)
display(submission_readiness)

required_passed = submission_readiness.loc[
    submission_readiness["required"],
    "passed",
].all()

# print(
#     "REQUIRED CHECKS:",
#     "PASS" if required_passed else "FAIL",
# )

# if exact_result is not None and len(set(exact_result["bits"])) == 1:
#     print(
#         "PRESENTATION WARNING: this batch has an all-equal optimum. "
#         "Use it as the business case, and pair it with a contested "
#         "mixed-decision run for the stronger optimization demonstration."
#     )

###################################################################
scaling_rows = []

for n_variables in [4, 8, 12, 20, 50, 100, 200]:
    pce_qubits = minimum_pce_qubits(
        n_variables
    )
    correlator_capacity = (
        3 * math.comb(pce_qubits, 2)
    )

    scaling_rows.append(
        {
            "master_variables": n_variables,
            "direct_qubits": n_variables,
            "compressed_pce_qubits": pce_qubits,
            "available_correlators": correlator_capacity,
            "variables_per_qubit": (
                n_variables / pce_qubits
            ),
            "qubit_reduction_pct": (
                100.0
                * (
                    1.0
                    - pce_qubits / n_variables
                )
            ),
        }
    )

scaling_analysis = pd.DataFrame(
    scaling_rows
)
display(scaling_analysis)

print("\nCurrent experiment")
print("Master variables:", N_MASTER_VARIABLES)
print("Compressed qubits:", N_QUBITS)
print(
    "Qubit reduction:",
    f"{100.0 * (1.0 - N_QUBITS / N_MASTER_VARIABLES):.2f}%",
)

################################################################
output_files = {
    "hybrid_order_recommendations.csv": final_recommendations,
    "method_comparison.csv": comparison,
    "pce_variable_mapping.csv": pce_mapping,
    "method_comparison.csv": comparison,
    "pce_variable_mapping.csv": pce_mapping,
    "pce_diagnostics.csv": pce_diagnostics,
    "pce_optimization_history.csv": pce_history,
    "postprocessing_trace.csv": postprocess_trace,
    "noise_diagnostics.csv": noise_diagnostics,
    "noise_trials.csv": noise_trials,
    "scaling_analysis.csv": scaling_analysis,
    "submission_readiness.csv": submission_readiness,
    "hybrid_line_level_allocation.csv": pd.DataFrame(
        hybrid_result["line_detail"]
    ),
}

for filename, dataframe in output_files.items():
    dataframe.to_csv(filename, index=False)
    print("Saved:", filename)

print(
    "\nFinal hybrid objective:",
    f"{hybrid_result['Z']:,.2f}",
)

if exact_result is not None:
    gap = (
        100.0
        * (
            exact_result["Z"]
            - hybrid_result["Z"]
        )
        / max(abs(exact_result["Z"]), 1.0)
    )
    print(
        "Exact objective:",
        f"{exact_result['Z']:,.2f}",
    )
    print(
        "Final gap to exact:",
        f"{gap:.4f}%",
    )



